[mypy]
warn_unused_configs = True

# Check the bodies of untyped functions too. Important for checking the __init__
# functions of classes, which often don't have a return type.
check_untyped_defs = True

# Specify files, or folders to check here separated with commas.
files = counter_app/src/counter_app/, counter_app/main.py
